# Mistia-Nexus/nginx-proxy/docker-compose.yml
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    ports:
      - '81:81'
      - '80:80'
      - '443:443'
    environment:
      DB_MYSQL_HOST: 'nginx-proxy_db'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: 'npm'
      DB_MYSQL_NAME: 'npm'
      DB_MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: nginx-proxy_db
    environment:
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped
