# This file contains the body of the deployment loop.
# It is called by deploy-services.yml for each item in the 'all_services' list.
- name: 'ACTION: Run deployment for {{ service.name }}.'
  tags: '{{ [service.name] + service.tags }}'
  block:
    - name: 'SETUP: Create .env file for {{ service.name }}.'
      ansible.builtin.template:
        src: 'templates/{{ service.name }}.env.j2'
        dest: '{{ deploy_path }}/{{ service.name }}/.env'
        mode: '0644'
        owner: '{{ ansible_user }}'
        group: 'admin'
      when: service.has_env
      become: no

    - name: 'ACTION: Deploy {{ service.name }}.'
      community.docker.docker_compose_v2:
        project_src: '{{ deploy_path }}/{{ service.name }}'
        state: present
        build: "{{ 'always' if service.has_build | default(false) else 'never' }}"
        pull: "{{ 'always' if not service.has_build | default(false) else 'never' }}"
      register: compose_result
      become: no

    - name: 'VERIFY: Wait for {{ service.name }} container to become healthy.'
      when: compose_result.changed
      community.docker.docker_container_info:
        name: '{{ service.name }}'
      register: container_info
      until: "container_info.container.State.Health.Status is defined and container_info.container.State.Health.Status == 'healthy'"
      retries: 20
      delay: 3
      become: no

  rescue:
    - name: 'HANDLE FAILURE: Process failure for critical service {{ service.name }}.'
      ansible.builtin.fail:
        msg: |
          Deployment or health check for critical service '{{ service.name }}' failed. Aborting.
          Please check logs with 'docker logs {{ service.name }}'.
          {% if compose_result is defined and compose_result.failed %}
          === Docker Compose Result ===
          {{ compose_result | to_nice_yaml }}
          {% endif %}
          {% if container_info is defined and container_info.failed %}
          === Health Check / Container Info Result ===
          {{ container_info | to_nice_yaml }}
          {% endif %}
      when: "'critical' in (service.tags | default([]))"

    - name: 'WARNING: Deployment of {{ service.name }} failed!'
      ansible.builtin.debug:
        msg: |
          Deployment or health check for non-critical service '{{ service.name }}' failed. Continuing play.
          Please check logs with 'docker logs {{ service.name }}'.
          {% if compose_result is defined and compose_result.failed %}
          === Docker Compose Result ===
          {{ compose_result | to_nice_yaml }}
          {% endif %}
          {% if container_info is defined and container_info.failed %}
          === Health Check / Container Info Result ===
          {{ container_info | to_nice_yaml }}
          {% endif %}
      when: "'critical' not in (service.tags | default([]))"
