# This file contains the body of the deployment loop.
# It is called by deploy-services.yml for each item in the 'all_services' list.
- name: 'ACTION: Run deployment for {{ service.name }}.'
  tags: '{{ [service.name] + service.tags }}'
  block:
    - name: 'SETUP: Create .env file for {{ service.name }}.'
      ansible.builtin.template:
        src: 'templates/{{ service.name }}.env.j2'
        dest: '{{ deploy_path }}/{{ service.name }}/.env'
        mode: '0644'
        owner: '{{ ansible_user }}'
        group: 'admin'
      when: service.has_env
      become: no

    - name: 'ACTION: Deploy {{ service.name }}.'
      community.docker.docker_compose_v2:
        project_src: '{{ deploy_path }}/{{ service.name }}'
        state: present
        build: "{{ 'always' if service.has_build | default(false) else 'never' }}"
        pull: "{{ 'always' if not service.has_build | default(false) else 'never' }}"
      register: compose_result
      become: no

    - name: 'VERIFY: Wait for {{ service.name }} container to become healthy.'
      when: compose_result.changed
      community.docker.docker_container_info:
        name: '{{ service.name }}'
      register: container_info
      until: "container_info.container.State.Health.Status is defined and container_info.container.State.Health.Status == 'healthy'"
      retries: 20
      delay: 3
      become: no

  rescue:
    - name: 'HANDLE FAILURE for {{ service.name }}'
      vars:
        # Determine the failure reason and craft a concise message.
        failure_reason: >-
          {% if compose_result is defined and compose_result.failed %}
          Docker Compose deployment failed. Error: {{ compose_result.stderr | default(compose_result.stdout) | default('No specific error message available.') }}
          {% elif container_info is defined and container_info.failed %}
          Health check failed. Last log: {{ ((container_info.container.State.Health.Log | default([])) | last).Output | default('No health log available.') | trim }}
          {% else %}
          An unknown error occurred during deployment or health check.
          {% endif %}

        # Construct the final message based on whether the service is critical.
        final_msg: >-
          {% if 'critical' in (service.tags | default([])) %}
          [CRITICAL] {{ failure_reason }} Aborting play.
          {% else %}
          [WARNING] {{ failure_reason }} Continuing play.
          {% endif %}
      block:
        - name: 'FAIL CRITICAL service {{ service.name }}'
          ansible.builtin.fail:
            msg: '{{ final_msg }}'
          when: "'critical' in (service.tags | default([]))"

        - name: 'WARN NON-CRITICAL service {{ service.name }}'
          ansible.builtin.debug:
            msg: '{{ final_msg }}'
          when: "'critical' not in (service.tags | default([]))"
