---
# Ansible Playbook to deploy Mistia-Nexus services
#
#  WSL Terminal:
#   cd ~/Mistia-Labs
#   source tools/activate.sh
#
# Example to run this playbook for all services:
#   nexus_deploy
#
# Example to run for only DNS-tagged services:
#   nexus_deploy --tags dns
#
# Example to run for only a specific service:
#   nexus_deploy --tags jellyfin
#
# Example to run for a new specific service:
#   nexus_deploy --tags sync,jellyfin
#
- name: Deploy Mistia-Nexus Services
  hosts: nexus
  become: yes
  gather_facts: no
  vars_files:
    - secrets.yml

  pre_tasks:
    - name: 'Setup'
      tags: always
      block:
        # - name: 'Setup Nexus Environment'
        #   import_tasks: tasks/setup.yml

        # - name: 'ACTION: Stat Caddyfile Before Sync'
        #   ansible.builtin.stat:
        #     path: '{{ deploy_path }}/caddy/Caddyfile'
        #   register: caddyfile_before

        - name: 'Git Synchronization'
          import_role:
            name: git_sync

        # - name: 'ACTION: Stat Caddyfile After Sync'
        #   ansible.builtin.stat:
        #     path: '{{ deploy_path }}/caddy/Caddyfile'
        #   register: caddyfile_after

        # - name: 'ACTION: Reload Caddy if Caddyfile Changed'
        #   ansible.builtin.debug:
        #     msg: 'Caddyfile changed, notifying handler.'
        #   when: caddyfile_before.stat.checksum != caddyfile_after.stat.checksum
        #   notify: 'Reload Caddy'
  tasks:
    - name: 'Deploy Nexus Services'
      tags: always
      import_tasks: tasks/deploy.yml

  post_tasks:
    - name: 'Synchronize Caddyfile'
      tags: sync
      import_role:
        name: caddy_sync

    - name: 'Synchronize AdGuard Home DNS Rewrites'
      #tags: sync
      import_role:
        name: dns_rewrite_sync

    - name: 'Synchronize Uptime Kuma Monitors'
      #tags: sync
      import_role:
        name: kuma_monitor_sync
