---
# Example to run this playbook for all services:
#   ansible-playbook deploy-services.yml
#
# Example to run for only DNS-tagged services:
#   ansible-playbook deploy-services.yml --tags dns
#
# Example to run for only a specific service (e.g., caddy):
#   ansible-playbook deploy-services.yml --tags caddy
#
# Example when adding new service, reload Caddy and deploy new service:
#   ansible-playbook deploy-services.yml --tags proxy-reload, jelly
- name: Deploy Mistia-Nexus Services
  hosts: nexus
  become: yes
  vars_files:
    - secrets.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3.11
    repo_root_path: '/volume2/docker'
    deploy_path: '{{ repo_root_path }}/mistia-nexus'

    # This is the master list of all services managed by this playbook.
    all_services:
      # --8<-- [start:adguard-home]
      - name: adguard-home
        tags: [critical, dns]
        has_env: false
        has_build: false
      # --8<-- [end:adguard-home]

      # --8<-- [start:caddy]
      - name: caddy
        tags: [critical, core, proxy]
        has_env: true
        has_build: true
      # --8<-- [end:caddy]

      # --8<-- [start:portainer]
      - name: portainer
        tags: [core, management]
        has_env: false
        has_build: false
      # --8<-- [end:portainer]

      # --8<-- [start:dockge]
      - name: dockge
        tags: [core, management]
        has_env: false
        has_build: false
      # --8<-- [end:dockge]

      # --8<-- [start:dozzle]
      - name: dozzle
        tags: [core, monitoring]
        has_env: false
        has_build: false
      # --8<-- [end:dozzle]

      # --8<-- [start:kuma]
      - name: kuma
        tags: [core, monitoring]
        has_env: false
        has_build: false
      # --8<-- [end:kuma]

      # --8<-- [start:duplicati]
      - name: duplicati
        tags: [core, backup]
        has_env: true
        has_build: false
      # --8<-- [end:duplicati]

      # --8<-- [start:tailscale]
      - name: tailscale
        tags: [core, vpn]
        has_env: true
        has_build: false
      # --8<-- [end:tailscale]

      # --8<-- [start:nextcloud]
      - name: nextcloud
        tags: [cloud]
        has_env: true
        has_build: true
      # --8<-- [end:nextcloud]

  pre_tasks:
    - name: 'VERIFY: Check for .git directory existence.'
      ansible.builtin.stat:
        path: '{{ repo_root_path }}/.git'
      register: git_dir_stat

    - name: 'FAIL: Abort if .git directory does not exist.'
      ansible.builtin.fail:
        msg: 'No .git directory found in {{ repo_root_path }}. Is this a git repo?'
      when: not git_dir_stat.stat.exists

    - name: 'VERIFY: Check if deploy_path exists.'
      ansible.builtin.stat:
        path: '{{ deploy_path }}'
      register: deploy_path_stat

    - name: 'FAIL: Abort if deploy_path does not exist.'
      ansible.builtin.fail:
        msg: 'deploy_path {{ deploy_path }} does not exist on the target host.'
      when: not deploy_path_stat.stat.exists

  tasks:
    # Synchronize the code on the NAS with your Git repository
    - name: 'ACTION: Synchronize Git repository on NAS.'
      tags: always
      ansible.builtin.shell: |
        set -e
        git fetch origin
        LOCAL_HASH=$(git rev-parse HEAD)
        REMOTE_HASH=$(git rev-parse origin/main)
        if [ "$LOCAL_HASH" != "$REMOTE_HASH" ]; then
            echo "Repository has changes. Resetting..."
            git reset --hard origin/main
            exit 0 # Indicate changed
        else
            echo "Repository is already up-to-date."
            exit 1 # Indicate no change
        fi
      args:
        chdir: '{{ deploy_path }}'
      become: no
      changed_when: 'git_sync_result.rc == 0'
      failed_when: 'git_sync_result.rc > 1'
      register: git_sync_result

    # Ensure the basic Docker network is in place
    - name: 'SETUP: Initial Docker network configuration.'
      tags: always
      block:
        - name: 'SETUP: Ensure mistia-proxy-net exists.'
          community.docker.docker_network:
            name: mistia-proxy-net
            state: present
            ipam_config:
              - subnet: '172.21.0.0/16'

    # Handle reloading the Caddy proxy configuration after changes
    - name: 'ACTION: Validate and Reload Caddy Configuration.'
      tags: [never, proxy-reload]
      block:
        - name: 'ACTION: Restart Caddy container to refresh Caddyfile bind mount.'
          community.docker.docker_container:
            name: caddy
            state: started
            restart: true

        - name: 'ACTION: Format Caddyfile using caddy fmt.'
          community.docker.docker_container_exec:
            container: caddy
            command: caddy fmt --overwrite /etc/caddy/Caddyfile
          register: caddy_validate_result
          changed_when: false
          failed_when: caddy_validate_result.rc != 0

        - name: 'ACTION: Reload Caddy with new configuration.'
          community.docker.docker_container_exec:
            container: caddy
            command: caddy reload --config /etc/caddy/Caddyfile
          changed_when: false

    # Main deployment loop: iterates over 'all_services' and calls the separate loop file for each item
    - name: 'ACTION: Deploy and Verify Services.'
      tags: always
      ansible.builtin.include_tasks: _deploy-service-loop.yml
      loop: '{{ all_services }}'
      loop_control:
        loop_var: service
