services:
  caddy:
    build: .
    container_name: caddy
    hostname: caddy
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    security_opt:
      - no-new-privileges:true
    user: "1000:10"
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    labels:
      - 'com.mistia-nexus.service.name=Caddy'
      - 'com.mistia-nexus.service.type=Reverse Proxy'
    environment:
      - TZ=Asia/Singapore
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - CADDY_EMAIL=${CADDY_EMAIL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
      - ./www:/srv/www
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/healthz']
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    restart: unless-stopped
    networks:
      - mistia-proxy-net

networks:
  mistia-proxy-net:
    name: mistia-proxy-net
    external: true
