services:
  caddy:
    build: .
    container_name: caddy
    hostname: caddy
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    labels:
      - 'com.mistia-nexus.service.name=Caddy'
      - 'com.mistia-nexus.service.type=Reverse Proxy'
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    environment:
      - TZ=Asia/Singapore
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - CADDY_EMAIL=${CADDY_EMAIL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./www:/srv/www
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/healthz']
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s
    dns:
      - 192.168.50.2 # AdGuard Home IP
    restart: unless-stopped
    networks:
      - mistia-proxy-net

networks:
  mistia-proxy-net:
    name: mistia-proxy-net
    driver: bridge
