services:
  filecloud-server:
    image: filecloud/fileclouddocker:24.1
    container_name: filecloud
    hostname: filecloud
    init: true
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '1.50'
          memory: 2048M
        reservations:
          cpus: '0.50'
          memory: 512M
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost/ || exit 1']
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - 'com.mistia-nexus.service.name=FileCloud'
      - 'com.mistia-nexus.service.type=Cloud Storage'
    environment:
      - TZ=Asia/Singapore
      - FILECLOUD_DB_TYPE=mongodb
      - FILECLOUD_DB_HOST=filecloud-db
      - FILECLOUD_DB_USER=${MONGO_INITDB_ROOT_USERNAME}
      - FILECLOUD_DB_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - FILECLOUD_SOLR_HOST=filecloud-solr
      - FILECLOUD_SOLR_PORT=8983
      - FILECLOUD_ADMIN_USER=${FILECLOUD_ADMIN_USER}
      - FILECLOUD_ADMIN_PASSWORD=${FILECLOUD_ADMIN_PASSWORD}
      - FILECLOUD_SERVER_LANG=en
    volumes:
      - filecloud_server_data:/var/www/html/data
      - filecloud_server_logs:/var/log/httpd
    depends_on:
      db:
        condition: service_healthy
      solr:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - filecloud-net
      - mistia-proxy-net

  db:
    image: mongo:6.0
    container_name: filecloud-db
    hostname: filecloud-db
    init: true
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M
        reservations:
          cpus: '0.50'
          memory: 256M
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    labels:
      - 'com.mistia-nexus.service.name=FileCloud Database'
      - 'com.mistia-nexus.service.type=Database'
    environment:
      - TZ=Asia/Singapore
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - filecloud_db_data:/data/db
    restart: unless-stopped
    networks:
      - filecloud-net

  solr:
    image: filecloud/solr:8.11
    container_name: filecloud-solr
    hostname: filecloud-solr
    init: true
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "solr-precreate filecloud_content_search && solr healthcheck -c filecloud_content_search"]
      interval: 1m
      timeout: 20s
      retries: 3
      start_period: 60s
    labels:
      - 'com.mistia-nexus.service.name=FileCloud Search'
      - 'com.mistia-nexus.service.type=Search'
    environment:
      - TZ=Asia/Singapore
    volumes:
      - filecloud_solr_data:/var/solr
    restart: unless-stopped
    networks:
      - filecloud-net

volumes:
  filecloud_server_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/docker/filecloud/server/data
  filecloud_server_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/docker/filecloud/server/logs
  filecloud_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/docker/filecloud/db
  filecloud_solr_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/docker/filecloud/solr

networks:
  filecloud-net:
    name: filecloud-net
  mistia-proxy-net:
    name: mistia-proxy-net
    external: true