services:
  [service-name]:
    image: [service-image]
    container_name: [service-name]
    hostname: [service-name]
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: [service-dependent]
          memory: [service-dependent]
        reservations:
          cpus: [service-dependent]
          memory: [service-dependent]
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:PORT/']
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - 'com.mistia-nexus.service.name=[service-name]'
      - 'com.mistia-nexus.service.type=[service-type]'
    environment:
      - TZ=Asia/Singapore
      - PUID=1000                    
      - PGID=10                   
    volumes:
      - host:container
    restart: unless-stopped
    # ports:
    #   - 'HOST_PORT:CONTAINER_PORT'  # <-- UNCOMMENT if direct access required
    networks:
      - mistia-proxy-net
    #sysctls:
    #  - net.ipv6.conf.all.disable_ipv6=1  # <-- Uncomment if you want to disable IPv6 for the service

#volumes: # <-- UNCOMMENT if you need to define volumes
#  [volume-name]:
#    driver: local

networks:
  mistia-proxy-net:
    name: mistia-proxy-net
    external: true
