# docker-compose.yml for AdGuard Home
services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    hostname: adguardhome
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1'
        ]
      interval: 5m
      timeout: 10s
      retries: 3
    labels:
      - 'com.mistia-nexus.service.name=AdGuard Home'
      - 'com.mistia-nexus.service.type=Network Security'
    environment:
      - TZ=Asia/Singapore
    networks:
      mistia_lan:
        # Assign a specific IP from the shared network's ip_range
        ipv4_address: 192.168.50.251
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    restart: unless-stopped

networks:
  mistia_lan:
    external: true
