services:
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    hostname: portainer
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test: ['CMD-SHELL', 'nc -z -v localhost 9000 || exit 1']
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - 'com.mistia-nexus.service.name=Portainer'
      - 'com.mistia-nexus.service.type=Management'
    environment:
      - TZ=Asia/Singapore
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    dns:
      - 192.168.50.251 # AdGuard Home IP
    restart: unless-stopped
    networks:
      - mistia-proxy-net

networks:
  mistia-proxy-net:
    name: mistia-proxy-net
    external: true
