# docker-compose.yml for Portainer CE
portainer:
  image: portainer/portainer-ce:latest
  container_name: portainer
  hostname: portainer
  logging:
    driver: 'json-file'
    options:
      max-size: '10m'
      max-file: '3'
  healthcheck:
    test: ['CMD', 'curl', '-fk', 'https://localhost:9443']
    interval: 5m
    timeout: 10s
    retries: 3
  labels:
    - 'com.mistia-nexus.service.name=Portainer'
    - 'com.mistia-nexus.service.type=Management'
  environment:
    - TZ=Asia/Singapore
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./data:/data
  ports:
    - 9444:9443
    - 8000:8000
  restart: unless-stopped
  networks:
    - portainer_net

networks:
portainer_net:
  name: portainer_net
