services:
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    hostname: portainer
    init: true
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    healthcheck:
      test: ['CMD-SHELL', 'nc -z -v localhost 9000 || exit 1']
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - 'com.mistia-nexus.service.name=Portainer'
      - 'com.mistia-nexus.service.type=Management'
    environment:
      - TZ=Asia/Singapore
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: unless-stopped
    networks:
      - mistia-proxy-net

networks:
  mistia-proxy-net:
    name: mistia-proxy-net
    external: true
