services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    hostname: duplicati
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run:exec
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8200']
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - 'com.mistia-nexus.service.name=Duplicati'
      - 'com.mistia-nexus.service.type=Backup'
    environment:
      - PUID=1000
      - PGID=10
      - TZ=Asia/Singapore
      - SETTINGS_ENCRYPTION_KEY=${DUPLICATI_SETTINGS_KEY}
      - DUPLICATI__WEBSERVICE_PASSWORD=${DUPLICATI_UI_PASSWORD}
    volumes:
      - ./config:/config
      - /:/nasroot:ro
    dns:
      - 192.168.50.2 # AdGuard Home IP
    restart: unless-stopped
    networks:
      - mistia-proxy-net

networks:
  mistia-proxy-net:
    name: mistia-proxy-net
    external: true
