# docker-compose.yml for Duplicati
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    hostname: duplicati
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8200']
      interval: 5m
      timeout: 10s
      retries: 3
    labels:
      - 'com.mistia-nexus.service.name=Duplicati'
      - 'com.mistia-nexus.service.type=Backup'
    environment:
      - PUID=1000
      - PGID=10
      - TZ=Asia/Singapore
      - SETTINGS_ENCRYPTION_KEY=${DUPLICATI_SETTINGS_KEY}
      - DUPLICATI__WEBSERVICE_PASSWORD=${DUPLICATI_UI_PASSWORD}
    volumes:
      - ./config:/config
      - /:/nasroot:ro
    ports:
      - 8100:8200
    restart: unless-stopped
    networks:
      - duplicati_net

networks:
  duplicati_net:
    name: duplicati_net
