# docker-compose.yml for Duplicati
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=10
      - TZ=Asia/Singapore
      - SETTINGS_ENCRYPTION_KEY=${DUPLICATI_SETTINGS_KEY}
      - PASSWORD=${DUPLICATI_UI_PASSWORD}
    volumes:
      - ./config:/config
      - /:/nasroot:ro
    ports:
      - 8200:8200
    restart: unless-stopped
