services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: mistia-nexus 
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test: ["CMD", "tailscale", "status"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - 'com.mistia-nexus.service.name=Tailscale'
      - 'com.mistia-nexus.service.type=Network Security'
    environment:
      - TZ=Asia/Singapore
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-routes=192.168.50.0/24 --advertise-exit-node --accept-dns=false
    volumes:
      - ./state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    network_mode: host
    restart: unless-stopped