services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: mistia-nexus
    init: true
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    security_opt:
      - no-new-privileges:true
    cap_add:
      - net_admin
      - sys_module
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 64M
    healthcheck:
      test: ["CMD", "tailscale", "status"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 20s
    labels:
      - 'com.mistia-nexus.service.name=Tailscale'
      - 'com.mistia-nexus.service.type=Network Security'
    environment:
      - TZ=Asia/Singapore
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-routes=192.168.50.0/24 --advertise-exit-node --accept-dns=false
    volumes:
      - ./state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    restart: unless-stopped
